### ISSUE TITLE
StubModule won't run in Intern (Dojo 2)

### ISSUE THREAD

**Issue by d0nk3y** [agrc/StubModule#7]
When running under Intern, StubModule generates an exception when trying to undefine the dependencies of the module being stubbed.  Here's the stack trace:

> TypeError: Cannot read property 'stubtest/ClassA' of undefined
>   at undefDependencies  \<util\stub-module.js:45:42\>
>   at \<util\stub-module.js:67:13\>
>   at execModule  \<node_modules\intern\node_modules\dojo\loader.ts:616:5\>
>   at \<node_modules\intern\node_modules\dojo\loader.ts:686:3\>
>   at guardCheckComplete  \<node_modules\intern\node_modules\dojo\loader.ts:664:3\>
>   at checkComplete  \<node_modules\intern\node_modules\dojo\loader.ts:673:23\>
>   at onLoadCallback  \<node_modules\intern\node_modules\dojo\loader.ts:757:4\>
>   at \<node_modules\intern\node_modules\dojo\loader.ts:848:4\>
>   at \<fs.js:334:14\>
>   at FSReqWrap.oncomplete  \<fs.js:95:15\>

and here's a snippet of the code that's generating the error:

```javascript
var undefDependencies = function (mod) {
    if (array.indexOf(processedDependencies, mod) !== -1 ||
        mod.indexOf('!') !== -1) {
        return;
    }
    processedDependencies.push(mod);

    array.forEach(require.modules[mod].deps, function (dep) {
        undefDependencies(dep.mid);
    });
```

I'm pretty sure the reason it's not working is because Intern is using a built version of Dojo that doesn't provide `require.modules`, while Jasmine is presumably using the full source.  I'm not sure if there's some other way to accomplish this or if I just need to make Intern use a different version of Dojo.  If it's the latter, it would be good to mention it in the StubModule documentation.

**Comment by stdavis** [comment]
Can you share the version of Intern that you are using along with your spec file?

**Comment by d0nk3y** [comment]
I'm using Intern 3.0.3, which uses Dojo 2.0 alpha 6.  My sample test just invokes StubModule and then asserts on something that will never pass.  That way I can comment out the forEach in stub-module.js and see that the assertion is executed, rather than stub-module throwing an exception.

```javascript
define([
  'intern!object',
  'intern/chai!expect',
  'util/stub-module'
], function (registerSuite, expect, stubModule) {
  registerSuite({

    notReallyATest: function () {
      return stubModule('stubtest/ClassA', {}).then(function (ClassA) {
        expect(true).to.be.false;
      });
    }

  });
});
```

ClassA.js is as simple as it gets:

```javascript
define([], function () {
  return {};
});
```

**Comment by stdavis** [comment]
Now I'm remembering issues with the Dojo 2 loader. I'll have to dig around to see what's up.

**Comment by stdavis** [comment]
@d0nk3y Take a look at the `dojo2` branch of this repo. I've configured it to use the dojo 2 loader (the same on that Intern uses) and have altered the code to make almost all of the tests pass. Give it a try and let me know if it works for you.

I also stumbled across the code on [this page](https://www.sitepen.com/blog/2014/07/14/mocking-data-with-intern/) which is very similar to StubModule but may work better for you.

**Comment by d0nk3y** [comment]
@stdavis Your dojo2 branch fixed the problem!  Thank you so much!

Regarding that other code you found, unless if I'm missing something, it doesn't look like you can inject a dynamic module like you can with StubModule.  That's exactly what had me so excited about StubModule, and now I'm even more excited since I can actually use it.  Thanks for writing this awesome script!

**Comment by stdavis** [comment]
Glad that it's working for you. You're correct about the SitePen example code. It only allows injecting separate modules not dynamic objects or functions. I'm closing this issue for now. Thanks for the heads up about intern.
